[versions]
target-sdk = "36"
android-gradle = "8.12.0"
kotlin = "2.2.0"
kotlinx-data-time = "0.7.1"
kotlinx-serialization = "1.9.0"
kotlinx-collections-immutable = "0.4.0"
androidx-compose-bom = "2025.07.00"
androidx-navigation = "2.9.3"
androidx-activity = "1.10.1"
androidx-datastore = "1.1.7"
androidx-splash-screen = "1.0.1"
androidx-benchmark = "1.4.0"
androidx-profileinstaller = "1.4.1"
androidx-hilt = "1.2.0"
hilt = "2.57"
ksp = "2.2.0-2.0.2"
room = "2.7.2"
spotless = "7.2.1"
git-hooks = "1.1.1"
protobuf-plugin = "0.9.5"
protobuf = "4.31.1"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash-screen" }
androidx-benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-profile-installer = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
kotlinx-date-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-data-time" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
protobuf-compiler = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-java-lite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-test = { id = "com.android.test", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
git-hooks = { id = "eu.bambooapps.gradle.plugin.githook", version.ref = "git-hooks" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
room = { id = "androidx.room", version.ref = "room" }
androidx-baseline-profile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
